site_name: AoC 2021
dev_addr: localhost:4001
docs_dir: consumer-docs
site_dir: docs
theme:
  logo: /assets/logo.png
  name: material
  palette:
    - scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - search.share
nav:
  - About: README.md
  - MD: markdown-test.md
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - extra
  - sane_lists
  - tables
